Updating steps in link-visio-drawing-to-a-specific-region.md
MicrosoftDocs/OfficeDocs-Support pull request #1369
Opened 2021-05-13 12:19 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1329.

2021-05-14 10:46 UTC, dariomws commented
Closes https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1349.

2021-05-19 14:42 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
> +3. On the Formulas menu, click Define Name.
```suggestion
3. On the Formulas menu, click **Define Name**.
```

2021-05-19 14:42 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
> +4. In the Define Name dialog box, type a unique name and then click OK.
```suggestion
4. In the Define Name dialog box, type a unique name and then click **OK**.
```

2021-05-19 14:43 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
>  7. On the Insert menu, click Object.
```suggestion
7. On the Insert menu, click **Object**.
```

2021-05-19 14:43 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
> +10. In the **Tell me what you want to do** box, type and click Links.
```suggestion
10. In the **Tell me what you want to do** box, type and click Links.
```

2021-05-19 14:44 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
>  12. In the Item Name box, type the name defined in step 4, and then click Open.
```suggestion
12. In the Item Name box, type the name defined in step 4, and then click **Open**.
```

2021-05-19 14:44 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
> +13. Click **Update Now**, and then click Close.
```suggestion
13. Click **Update Now**, and then click **Close**.
```

2021-05-19 14:49 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
> +11. In the Links dialog box, select the link to the Excel worksheet, click **Automatic** under Update, and then click **Change Source**.
```suggestion
11. In the Links dialog box, select the link to the Excel worksheet, choose **Automatic** under Update, and then select **Change Source**.
```

2021-05-19 14:53 UTC, JohanFreelancer9 commented on Office/Client/excel/link-visio-drawing-to-a-specific-region.md
>  7. On the Insert menu, click Object.
```suggestion
7. On the Insert menu, click **Object**.
```

2021-05-19 14:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-19 15:01 UTC, JohanFreelancer9 approved these changes

2021-05-22 13:40 UTC, merged