Update migrationpermanentexception-when-moving-mailboxes.md
MicrosoftDocs/OfficeDocs-Support pull request #1375
Opened 2021-05-13 22:46 UTC by msbemba

Added a line to enclose the value in double quotation marks as Exchange guid has hyphens.

2021-05-13 22:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1010

2021-05-19 09:53 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/move-mailboxes/migrationpermanentexception-when-moving-mailboxes.md
> +4. Run the following command to set the value of the `ExchangeGUID` property on the on-premises remote mailbox to the value that you retrieved in step 3 and Enclose the whole Guid in double quotation
```suggestion
4. Run the following command to set the value of the `ExchangeGUID` property on the on-premises remote mailbox to the value that you retrieved in step 3 and enclose the whole GUID in double quotation marks.
```

2021-05-19 09:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-19 15:43 UTC, JohanFreelancer9 approved these changes

2021-05-20 10:32 UTC, merged