Update information-about-the-outlook-autocomplete-list.md
MicrosoftDocs/OfficeDocs-Support pull request #1437
Opened 2021-05-20 17:10 UTC by msbemba

Made changes to the article to include outlook 2019

2021-05-20 17:11 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1092

2021-05-22 04:24 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +#### Outlook 2010, Outlook 2013, Outlook 2016 and Outlook 2019
```suggestion
#### Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019
```

2021-05-22 04:25 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +### How to import .nk2 files into Outlook 2010, Outlook 2013, Outlook 2016 and Outlook 2019
```suggestion
### How to import .nk2 files into Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019
```

2021-05-22 04:25 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +Microsoft Office Outlook 2007 and earlier versions store the AutoComplete list in a nickname (.nk2) file on the disk. Outlook 2010, Outlook 2013, and Outlook 2016 store the AutoComplete list as a hid
```suggestion
Microsoft Office Outlook 2007 and earlier versions store the AutoComplete list in a nickname (.nk2) file on the disk. Outlook 2010, Outlook 2013, and Outlook 2016 store the AutoComplete list as a hidden message in your primary message store. Outlook 2010, Outlook 2013, Outlook 2016, and outlook 2019 let you import the older .nk2 files.
```

2021-05-22 04:29 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +##### Outlook 2010, Outlook 2013, Outlook 2016 and Outlook 2019
```suggestion
##### Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019
```

2021-05-22 04:29 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +To copy the AutoComplete list in Outlook 2010, Outlook 2013, Outlook 2016 and Outlook 2019 follow these steps:
```suggestion
To copy the AutoComplete list in Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019, follow these steps:
```

2021-05-22 04:30 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
> +##### Outlook 2010, Outlook 2013, Outlook 2016 and Outlook 2019
```suggestion
##### Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019
```

2021-05-22 04:32 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/information-about-the-outlook-autocomplete-list.md
>  Use one of the following two methods to delete the AutoComplete list in Outlook 2010, Outlook 2013, and Outlook 2016.
```suggestion
Use one of the following two methods to delete the AutoComplete list in Outlook 2010, Outlook 2013, Outlook 2016, and Outlook 2019.
```

2021-05-22 04:36 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, please commit my suggested changes. Many thanks.

2021-05-22 10:09 UTC, merged