update limit exceed effects
MicrosoftDocs/OfficeDocs-Support pull request #1488
Opened 2021-05-28 06:10 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1150

2021-05-28 06:11 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-05-28 07:09 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md
> +Exceeding per minute limit may cause some delivery delay, exceeding recipients per day limit causes the following error:
```suggestion
Exceeding the per minute limit may cause some delivery delays. Exceeding the recipients per day limit causes the following error:  
```

2021-05-28 07:10 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-03 08:39 UTC, JohanFreelancer9 approved these changes

2021-07-19 07:00 UTC, merged