added note about classic OWA
MicrosoftDocs/OfficeDocs-Support pull request #1541
Opened 2021-06-06 16:53 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/442

2021-06-06 16:54 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-06-07 02:34 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/administration/update-contact-information.md
> +> The below instruction is only applicable to the classic OWA, available at [this URL](https://outlook.office365.com/owa/?path=/classic). It will be deprecated in future, and you may need to use alte
```suggestion
> The following instructions are only applicable to the classic [Outlook Web App](https://outlook.office365.com/owa/?path=/classic). It will be deprecated in future, and you may need to use alternative ways to update your profile information, like using [Microsoft 365 Delve](https://support.microsoft.com/office/view-and-update-your-profile-in-delve-4e84343b-eedf-45a1-aeb9-8627ccca14ba).
```

2021-06-07 02:35 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-08 04:58 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
could you please have one more look? I didn't apply your suggestion, since outlook web app is not a correct term

Thank you

2021-06-08 05:59 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/administration/update-contact-information.md
> +> The following instructions are only applicable to the classic [Outlook on the Web](https://outlook.office365.com/owa/?path=/classic). It will be deprecated in future, and you may need to use altern
```suggestion
> The following instructions are only applicable to the classic [Outlook on the Web](https://outlook.office365.com/owa/?path=/classic). It will be deprecated in the future, and you may need to use alternative ways to update your profile information, like using [Microsoft 365 Delve](https://support.microsoft.com/office/view-and-update-your-profile-in-delve-4e84343b-eedf-45a1-aeb9-8627ccca14ba).
```

2021-06-08 06:02 UTC, JohanFreelancer9 requested changes
@MaratMussabekov - agree, looks good. Just one more minor edit, please.

2021-06-08 07:04 UTC, merged