Update sign-in-loop.md
MicrosoftDocs/OfficeDocs-Support pull request #1614
Opened 2021-06-22 18:16 UTC by msbemba

added firefox to the list

2021-06-22 18:17 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1386

2021-06-23 13:28 UTC, JohanFreelancer9 commented on Teams/teams-sign-in/sign-in-loop.md
> +Change Microsoft Edge, Internet Explorer, Mozilla Firefox or Google Chrome settings using administrator rights or a Group Policy object (GPO).
```suggestion
Change Microsoft Edge, Internet Explorer, Mozilla Firefox, or Google Chrome settings using administrator rights or a Group Policy object (GPO).
```

2021-06-23 13:29 UTC, JohanFreelancer9 commented on Teams/teams-sign-in/sign-in-loop.md
> +1. Click the **Menu** button , then select **Preferences**.
```suggestion
1. Select the **Menu** button, then select **Preferences**.
```

2021-06-23 13:32 UTC, JohanFreelancer9 commented on Teams/teams-sign-in/sign-in-loop.md
> +7. Click **Save Changes**.
```suggestion
1. Click the **Menu** button, then select **Preferences**.
2. Select **Privacy**.
3. Check the box to the left of **Accept cookies from sites**.
4. Next to **Accept third party cookies**, select **Always** from the menu.
5. On the bottom right of the window, **select Exceptions**.
6. In the **Address of website:** text box, type the websites listed below, clicking the **Allow** button after each one.
    - `https://*.microsoft.com`
    - `https://*.microsoftonline.com`
    - `https://*.teams.skype.com`
    - `https://*.teams.microsoft.com`
    - `https://*.sfbassets.com`
    - `https://*.skypeforbusiness.com`

7. Select **Save Changes**.
```

2021-06-23 13:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-23 15:04 UTC, JohanFreelancer9 approved these changes

2021-07-20 08:29 UTC, merged

2021-07-20 13:39 UTC, simonxjx commented
![image](https://user-images.githubusercontent.com/16147799/126334017-e52d7e91-1846-495a-a536-1f85ad679947.png)