update steps
MicrosoftDocs/OfficeDocs-Support pull request #1655
Opened 2021-07-03 11:18 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1645

2021-07-03 11:18 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-07-04 08:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/administration/how-to-change-your-user-photo.md
> +4. In the appeared **Change your photo** window, select **Upload a new photo** to select and upload your photo.
```suggestion
4. In the **Change your photo** window that appears, select **Upload a new photo** to select and upload your photo.
```

2021-07-04 08:44 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/administration/how-to-change-your-user-photo.md
> +- A high-resolution photo is stored in the root directory of the user's Exchange Online mailbox. High-resolution photos are displayed in Exchange Online, Lync 2013, Skype for Business and Teams.
```suggestion
- A high-resolution photo is stored in the root directory of the user's Exchange Online mailbox. High-resolution photos are displayed in Exchange Online, Lync 2013, Skype for Business, and Microsoft Teams.
```

2021-07-04 08:44 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-06 09:15 UTC, merged