added section about OWA
MicrosoftDocs/OfficeDocs-Support pull request #1660
Opened 2021-07-06 01:41 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1604

2021-07-06 01:41 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-07-06 06:45 UTC, JohanFreelancer9 commented on Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md
> +# How to remove the Get and set up Outlook Mobile app on my phone option from Outlook and Outlook on the Web
```suggestion
# How to remove the Get and set up Outlook Mobile app on my phone option from Outlook and Outlook on the web
```

2021-07-06 06:46 UTC, JohanFreelancer9 commented on Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md
> +Microsoft Outlook 2016, Outlook 2019, Outlook for Office 365 and Outlook on the Web (OWA) offer an option to set up the Outlook Mobile app for your phone. The option appears in four places in Outlook
```suggestion
Microsoft Outlook 2016, Outlook 2019, Outlook for Office 365, and Outlook on the web (OWA) offer an option to set up the Outlook Mobile app for your phone. The option appears in four places in Outlook:
```

2021-07-06 06:47 UTC, JohanFreelancer9 commented on Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md
> +## How to remove this option in Outlook on the Web
```suggestion
## How to remove this option in Outlook on the web
```

2021-07-06 06:47 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-07 09:05 UTC, JohanFreelancer9 commented on Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md
> +1. [Connect to Exchange Online PowerShell](/powershell/exchange/connect-to-exchange-online-powershell)
```suggestion
1. [Connect to Exchange Online PowerShell](/powershell/exchange/connect-to-exchange-online-powershell).
```

2021-07-07 09:06 UTC, JohanFreelancer9 requested changes
Apologies @MaratMussabekov, one more, please.

2021-07-09 03:55 UTC, merged