Update applies to section
MicrosoftDocs/OfficeDocs-Support pull request #1696
Opened 2021-07-24 17:27 UTC by MaratMussabekov

2021-07-24 17:28 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information. PR is not related to any issue raised by users.

Thank you

2021-07-25 06:49 UTC, JohanFreelancer9 commented on Outlook/Client/user-interface/default-folder-is-missing.md
> +- Exchange Server 2016
```suggestion
```

2021-07-25 06:50 UTC, JohanFreelancer9 requested changes
Copy review - please remove the duplicate line.

2021-07-26 07:07 UTC, JohanFreelancer9 approved these changes

2021-07-27 06:09 UTC, merged