Update cannot-move-meetings-between-calendars.md
MicrosoftDocs/OfficeDocs-Support pull request #1723
Opened 2021-08-05 14:48 UTC by msbemba

Added a workaround to forward the meeting to the other account.

2021-08-05 14:48 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1707

2021-08-06 04:33 UTC, JohanFreelancer9 commented on Outlook/Mac/calendars/cannot-move-meetings-between-calendars.md
> +The workaround is to forward the meeting to the account that you want the calendar item to be moved.
```suggestion
The workaround is to forward the meeting to the account that you want the calendar item to be moved to. 
```

2021-08-06 04:34 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-08-06 05:22 UTC, JohanFreelancer9 approved these changes

2021-08-10 06:42 UTC, merged