Update cannot-expand-nested-contact-groups-unknown-shown.md
MicrosoftDocs/OfficeDocs-Support pull request #1726
Opened 2021-08-05 16:21 UTC by msbemba

Updated another resolution to remove the lost members

2021-08-05 16:21 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1718

2021-08-06 04:53 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/cannot-expand-nested-contact-groups-unknown-shown.md
> +1) Open the group, Select **Update now**. If there are members that cannot be found, outlook will prompt you to choose between the three below options
```suggestion
1) Open the group and select **Update now**. If there are members that cannot be found, Outlook will prompt you to choose between the following three options:
```

2021-08-06 04:54 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/cannot-expand-nested-contact-groups-unknown-shown.md
> +  - Try to repair  the lost members and remove only those that cannot be resolved.
```suggestion
  - Try to repair the lost members and remove only those that cannot be resolved.
```

2021-08-06 04:55 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/cannot-expand-nested-contact-groups-unknown-shown.md
> +2) Select, **Try to repair  the lost members and remove only those that cannot be resolved** and click **Ok**.
```suggestion
2) Choose **Try to repair the lost members and remove only those that cannot be resolved** and select **Ok**.
```

2021-08-06 04:58 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly commit the suggested changes. Many thanks.

2021-08-06 06:38 UTC, JohanFreelancer9 approved these changes

2021-08-10 05:54 UTC, merged