Step 5 does not show the option
MicrosoftDocs/OfficeDocs-Support pull request #1735
Opened 2021-08-11 05:58 UTC by joinimran

In step 5, users is not getting the option to update the settings even if they are eligible for an upgrade. Based on the test and feedback from the user, I have added a note to contact Microsoft Support if a user is not getting the option to update the quota.

Problem: https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1686

2021-09-04 06:02 UTC, JohanFreelancer9 commented on SharePoint/OneDrive/storage/check-storage-increase-eligibility.md
> +> If you are not receiving option to update settings, contact [Microsoft Support](https://go.microsoft.com/fwlink/?linkid=869559) to enable boost storage for your tanent.
```suggestion
> If you do not receive the option to update settings, contact [Microsoft Support](https://go.microsoft.com/fwlink/?linkid=869559) to enable boost storage for your tenant. 
```

2021-09-04 06:03 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-06 08:15 UTC, JohanFreelancer9 approved these changes

2021-09-15 09:10 UTC, helenclu commented
Change rejected by SPM.

2021-09-15 09:10 UTC, closed without merging