modified information about groups
MicrosoftDocs/OfficeDocs-Support pull request #1803
Opened 2021-09-08 11:03 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1780

2021-09-08 11:03 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-09-08 13:51 UTC, JohanFreelancer9 commented on Outlook/Client/contacts/cannot-manage-distribution-group-exchange-mailbox.md
> +Distribution groups are configured to be managed by other distribution and security groups. Unfortunately, in Exchange Server 2010 and later, you could only use mail-enabled security groups or indivi
```suggestion
Distribution groups are configured to be managed by other distribution and security groups. However, in Exchange Server 2010 and later you can only use mail-enabled security groups or individual users to manage distribution groups. 
```

2021-09-08 13:53 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-13 17:06 UTC, JohanFreelancer9 approved these changes

2021-09-15 08:50 UTC, merged