added one more option
MicrosoftDocs/OfficeDocs-Support pull request #1834
Opened 2021-09-17 10:16 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/1790

2021-09-17 10:17 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-09-17 14:11 UTC, JohanFreelancer9 commented on Office/Client/word/object-not-appear-in-word-2010.md
> +- The **Show field codes instead of their values** option is turned on
```suggestion
- The **Show field codes instead of their values** option is turned on.
```

2021-09-17 14:12 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-18 05:46 UTC, JohanFreelancer9 approved these changes

2021-09-28 09:20 UTC, merged