Update email-stuck-queues.md
MicrosoftDocs/OfficeDocs-Support pull request #1898
Opened 2022-03-22 12:51 UTC by Kovai-MSFT

Updated the article with aspects of Hot Recipients and SRP limit changes which can potentially lead to queue build up at On-premises end.

2022-03-23 12:03 UTC, stanalek commented on Exchange/ExchangeServer/mailflow/email-stuck-queues.md
> +In Microsoft Exchange Server 2019, 2016, or 2013, email messages may be stuck in on-premises message queues for several minutes if the server is configured to send to a single destination, such as Ex
1. I would keep English simple for sake of making it easy for non-native speakers and auto-translation tools.
2. SRP should still be defined here as it is used as "SRP" later on.

2022-03-23 12:07 UTC, stanalek approved these changes

2022-03-23 18:19 UTC, Kovai-MSFT commented on Exchange/ExchangeServer/mailflow/email-stuck-queues.md
> +In Microsoft Exchange Server 2019, 2016, or 2013, email messages may be stuck in on-premises message queues for several minutes if the server is configured to send to a single destination, such as Ex
Let's hold off on this for now based on Michelle's comments

2022-03-25 15:42 UTC, stanalek commented on Exchange/ExchangeServer/mailflow/email-stuck-queues.md
> +In Microsoft Exchange Server 2019, 2016, or 2013, email messages may be stuck in on-premises message queues for several minutes if the server is configured to send to a single destination, such as Ex
Ok, not sure what I need to do on this GitHub review

2022-03-25 17:38 UTC, stanalek requested changes
Putting this one on hold for now.

2024-09-12 07:22 UTC, closed without merging